import { useEffect, useMemo, useRef, useState } from 'react';
import { LoaderCircle, TriangleAlert } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import { ChartInstance, ChartRequest, ChartResult, DatasetProfile } from '../types';
import { Language, text } from '../i18n';
import { formatNumber } from '../formatting';
const palette = ['#4f46e5', '#0f766e', '#c2410c', '#be185d'];
interface Props { instance: ChartInstance; profile: DatasetProfile; language: Language; onPin: (id: string, chart: ChartResult, request: ChartRequest) => void; onViewRecords?: (chart: ChartResult, request: ChartRequest) => void; }
export default function ExecutiveChartCard({ instance, profile, language, onPin, onViewRecords }: Props) {
 const dimensions = useMemo(() => profile.columns.filter(c => c.kind === 'cat' || c.kind === 'time'), [profile]); const metrics = useMemo(() => profile.columns.filter(c => c.kind === 'num'), [profile]);
 const [request, setRequest] = useState<ChartRequest>(instance.request); const [result, setResult] = useState<ChartResult | null>(instance.result ?? null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const sequence = useRef(0);
 useEffect(() => { setRequest(instance.request); setResult(instance.result ?? null); setError(null); }, [instance.id, profile.run_id]);
 const fingerprint = JSON.stringify({ run: profile.run_id, language, request });
 useEffect(() => { if (result && request === instance.request) return; const controller = new AbortController(); const id = ++sequence.current; setLoading(true); setError(null); fetch(`/api/runs/${profile.run_id}/chart?language=${language}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request), signal: controller.signal }).then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.detail || text(language, 'chartRejected')); return body as ChartResult; }).then(body => { if (id === sequence.current) setResult(body); }).catch(reason => { if (id === sequence.current && (reason as Error).name !== 'AbortError') setError(reason instanceof Error ? reason.message : text(language, 'chartUpdateFailed')); }).finally(() => { if (id === sequence.current) setLoading(false); }); return () => controller.abort(); // fingerprint is the explicit request trigger
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, [fingerprint]);
 const grouped = Boolean(request.secondary_dimension); const types: ChartRequest['chart_type'][] = request.x_metric ? ['scatter'] : grouped ? ['bar', 'stacked_bar'] : ['bar', 'line', 'area', 'pie', 'donut'];
 const update = (next: ChartRequest) => setRequest(next);
 return <article className={`executive-chart-card role-${instance.role}`}><header className="chart-card-header"><div><p className="section-eyebrow">{instance.role === 'trend' ? text(language, 'primaryTrend') : text(language, 'customChart')}</p><h2>{result?.title ?? instance.title}</h2></div>{loading && <span className="chart-status"><LoaderCircle className="w-3.5 h-3.5 animate-spin" />{text(language, 'updating')}</span>}</header><div className="chart-controls"><label>{text(language, 'metric')}<select value={request.metric} onChange={e => update({ ...request, metric: e.target.value })}>{metrics.map(x => <option key={x.name}>{x.name}</option>)}</select></label><label>{text(language, 'dimension')}<select value={request.dimension} onChange={e => update({ ...request, dimension: e.target.value })}>{dimensions.map(x => <option key={x.name}>{x.name}</option>)}</select></label><label>{text(language, 'type')}<select value={types.includes(request.chart_type) ? request.chart_type : types[0]} onChange={e => update({ ...request, chart_type: e.target.value as ChartRequest['chart_type'], x_metric: e.target.value === 'scatter' ? metrics.find(x => x.name !== request.metric)?.name : undefined })}>{types.map(x => <option key={x}>{x}</option>)}</select></label></div>{error && <p className="chart-error"><TriangleAlert className="w-4 h-4" />{error}</p>}<div className="h-64">{result ? <Chart result={result} language={language} /> : <p>{text(language, 'chartConfigure')}</p>}</div>{result && <footer><button onClick={() => onPin(instance.id, result, request)}>{text(language, 'addReport')}</button>{onViewRecords && <button onClick={() => onViewRecords(result, request)}>{text(language, 'viewRecords')}</button>}</footer>}</article>;
}
function Chart({ result, language }: { result: ChartResult; language: Language }) { const metric = result.metric_display_name ?? result.metric; const tip = (v: number) => [formatNumber(v, language), metric]; if (result.chart_type === 'pie' || result.chart_type === 'donut') return <ResponsiveContainer><PieChart><Tooltip formatter={tip}/><Legend/><Pie data={result.rows} dataKey="value" nameKey="display_label" innerRadius={result.chart_type === 'donut' ? 50 : 0}>{result.rows.map((_, i) => <Cell key={i} fill={palette[i % palette.length]}/>)}</Pie></PieChart></ResponsiveContainer>; if (result.chart_type === 'scatter') return <ResponsiveContainer><ScatterChart><CartesianGrid/><XAxis dataKey="x_value" name="X"/><YAxis dataKey="value" name={metric}/><Tooltip formatter={tip} labelFormatter={(_, p) => p[0]?.payload?.display_label ?? ''}/><Scatter data={result.rows} fill={palette[0]}/></ScatterChart></ResponsiveContainer>; const C = result.chart_type === 'line' ? LineChart : result.chart_type === 'area' ? AreaChart : BarChart; const Mark = result.chart_type === 'line' ? Line : result.chart_type === 'area' ? Area : Bar; return <ResponsiveContainer><C data={result.rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="display_label"/><YAxis tickFormatter={v => formatNumber(v, language, true)}/><Tooltip formatter={tip}/><Legend/><Mark dataKey="value" name={metric} stroke={palette[0]} fill={palette[0]}/></C></ResponsiveContainer>; }
