import { Download, FileText, LayoutTemplate, Printer } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { CustomReportArtifact, CustomReportDocument } from '../types';
import { Language, text } from '../i18n';
import ValidatedChart from './ValidatedChart';

type Template = 'executive_briefing' | 'sales_performance_review' | 'category_division_deep_dive' | 'weekly_monthly_business_review';
type Blueprint = { id: Template; title: string; description: string; sections: string[]; slots: Array<{ key: string; label: string; accepts: SlotKind[] }> };
type SlotKind = 'trend' | 'ranking' | 'share' | 'evidence';

const blueprints: Blueprint[] = [
  { id: 'executive_briefing', title: 'Executive Briefing', description: 'Cover, KPI evidence strip, synthesis, drivers, risks and actions.', sections: ['Executive synthesis', 'Growth highlights', 'Risks and watchouts', 'Numbered action plan'], slots: [{ key: 'kpi-evidence', label: 'KPI benchmark strip', accepts: ['evidence'] }, { key: 'growth', label: 'Growth highlights', accepts: ['trend'] }, { key: 'drivers', label: 'Value drivers', accepts: ['ranking', 'share'] }] },
  { id: 'sales_performance_review', title: 'Sales Performance Review', description: 'Period comparison, hero trend, drivers and channel contribution.', sections: ['Risks and opportunities', 'Sales actions'], slots: [{ key: 'hero-trend', label: 'Hero sales trend', accepts: ['trend'] }, { key: 'ranking-share', label: 'Drivers and contribution', accepts: ['ranking', 'share'] }, { key: 'sales-kpis', label: 'Sales KPI evidence', accepts: ['evidence'] }] },
  { id: 'category_division_deep_dive', title: 'Category / Division Deep Dive', description: 'Scope, segment comparison, rankings, evidence and segment actions.', sections: ['Segment evidence', 'Actions by segment'], slots: [{ key: 'contribution-ranking', label: 'Contribution and ranking', accepts: ['ranking'] }, { key: 'comparison', label: 'Segment comparison', accepts: ['share', 'trend'] }, { key: 'evidence', label: 'Evidence callouts', accepts: ['evidence'] }] },
  { id: 'weekly_monthly_business_review', title: 'Weekly / Monthly Business Review', description: 'Period snapshot, previous-period view, decisions and owner tracker.', sections: ['Wins and watchouts', 'Decisions', 'Owner / action / deadline tracker'], slots: [{ key: 'period-snapshot', label: 'Period snapshot', accepts: ['evidence'] }, { key: 'trend-grid', label: 'Compact trend grid', accepts: ['trend', 'ranking', 'share'] }, { key: 'previous-comparison', label: 'Previous-period comparison', accepts: ['evidence'] }] },
];

const empty = (runId: string): CustomReportDocument => ({ run_id: runId, title: 'Custom Report', executive_summary: '', sections: [], pinned_artifacts: [], manual_glossary_notes: [], glossary: [], updated_at: '', layout_blueprint: { template: 'executive_briefing' } });
const artifactKind = (artifact: CustomReportArtifact): SlotKind => {
  const result = artifact.result;
  if (!result) return 'evidence';
  if (result.chart_type === 'line' || result.chart_type === 'area' || result.sort_mode === 'chronological') return 'trend';
  if (result.chart_type === 'pie' || result.chart_type === 'donut') return 'share';
  if (result.chart_type === 'bar' || result.chart_type === 'pareto' || result.chart_type === 'stacked_bar') return 'ranking';
  return 'evidence';
};
const localize = (language: Language, en: string, vi: string) => language === 'vi' ? vi : en;

type Props = { runId: string; report: CustomReportDocument | null; language: Language; onChange: (next: CustomReportDocument) => void };
export default function ReportComposer({ runId, report, language, onChange }: Props) {
  const [draft, setDraft] = useState<CustomReportDocument>(() => report ?? empty(runId));
  const [template, setTemplate] = useState<Template>('executive_briefing');
  const [status, setStatus] = useState('');
  const ref = useRef(draft); const queue = useRef(Promise.resolve());
  useEffect(() => { const next = report ?? empty(runId); ref.current = next; setDraft(next); setTemplate((next.layout_blueprint?.template ?? 'executive_briefing') as Template); }, [report, runId]);
  const save = (next = ref.current, chosen = template) => { ref.current = next; setDraft(next); setStatus(text(language, 'saving')); queue.current = queue.current.then(async () => { const response = await fetch(`/api/runs/${runId}/custom-report`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...next, locale: language, layout_blueprint: { template: chosen } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || text(language, 'reportSaveFailed')); ref.current = body as CustomReportDocument; setDraft(ref.current); onChange(ref.current); setStatus(text(language, 'saved')); }).catch(error => setStatus(error instanceof Error ? error.message : text(language, 'reportSaveFailed'))); };
  const changeTemplate = (next: Blueprint) => { setTemplate(next.id); const update = { ...ref.current, title: ref.current.title === 'Custom Report' ? next.title : ref.current.title, layout_blueprint: { template: next.id } }; void save(update, next.id); };
  const update = <K extends keyof CustomReportDocument>(key: K, value: CustomReportDocument[K]) => { const next = { ...ref.current, [key]: value }; ref.current = next; setDraft(next); };
  const blueprint = blueprints.find(item => item.id === template) ?? blueprints[0];
  const slotArtifacts = (slot: Blueprint['slots'][number]) => draft.pinned_artifacts.filter(artifact => slot.accepts.includes(artifactKind(artifact)));
  return <section className="report-composer"><header className="report-composer-header"><div><p className="section-eyebrow">{text(language, 'reportEyebrow')}</p><h1>{text(language, 'reportTitle')}</h1><p>{text(language, 'reportSub')}</p></div><div className="report-actions"><span aria-live="polite">{status}</span><button onClick={() => save()}>{text(language, 'save')}</button><button onClick={() => window.open(`/api/runs/${runId}/report`, '_blank', 'noopener,noreferrer')}><Download size={15}/>{text(language, 'exportHtml')}</button><button onClick={() => window.print()}><Printer size={15}/>{text(language, 'printPdf')}</button></div></header>
    <section className="report-template-gallery"><div><p className="section-eyebrow">{text(language, 'reportBlueprintEyebrow')}</p><h2><LayoutTemplate size={17}/>{text(language, 'reportBlueprints')}</h2><p>{text(language, 'reportBlueprintHelp')}</p></div><div className="template-cards">{blueprints.map(item => <button type="button" className={item.id === template ? 'active' : ''} key={item.id} onClick={() => changeTemplate(item)}><strong>{item.title}</strong><span>{item.description}</span><em>{text(language, 'applyLayout')}</em></button>)}</div></section>
    <div className="report-layout"><div className="report-editor"><label>{text(language, 'reportTitleLabel')}<input value={draft.title} maxLength={120} onChange={event => update('title', event.target.value)} onBlur={() => save()}/></label><label>{text(language, 'executiveSummary')}<textarea value={draft.executive_summary} rows={4} onChange={event => update('executive_summary', event.target.value)} onBlur={() => save()}/></label><label>{text(language, 'sectionsRecommendations')}<textarea value={draft.sections.map(section => `${section.heading}: ${section.commentary}`).join('\n')} rows={6} onChange={event => update('sections', event.target.value.split('\n').filter(Boolean).map((line, index) => { const [heading, ...rest] = line.split(':'); return { section_id: `section-${index}`, heading: heading.trim(), commentary: rest.join(':').trim(), recommended_actions: [] }; }))} onBlur={() => save()}/></label></div>
      <section className={`report-preview report-preview-${template}`} aria-label={localize(language, `${blueprint.title} preview`, `Xem trước ${blueprint.title}`)}><div className="preview-cover"><p className="section-eyebrow">{blueprint.title}</p><h2>{draft.title}</h2><p>{draft.executive_summary || localize(language, 'Add an evidence-grounded executive synthesis.', 'Thêm phần tổng hợp điều hành dựa trên bằng chứng.')}</p></div><div className="preview-slots">{blueprint.slots.map(slot => <PreviewSlot key={slot.key} label={slot.label} artifacts={slotArtifacts(slot)} language={language}/>)}</div><div className="preview-sections">{draft.sections.length ? draft.sections.map(section => <article key={section.section_id}><h3>{section.heading}</h3><p>{section.commentary || localize(language, 'Add grounded commentary or actions.', 'Thêm nhận định hoặc hành động có căn cứ.')}</p></article>) : <article className="slot-empty"><FileText size={16}/>{localize(language, 'Add sections for decisions, actions, or notes.', 'Thêm phần quyết định, hành động hoặc ghi chú.')}</article>}</div></section></div>
  </section>;
}
function PreviewSlot({ label, artifacts, language }: { label: string; artifacts: CustomReportArtifact[]; language: Language }) { return <article className="preview-slot"><h3>{label}</h3>{artifacts.length ? artifacts.map(artifact => <div className="preview-artifact" key={artifact.artifact_id}>{artifact.result ? <ValidatedChart result={artifact.result} language={language} compact report/> : <p>{artifact.title}</p>}</div>) : <div className="slot-empty"><FileText size={15}/>{localize(language, 'Empty — pin a matching validated artifact.', 'Trống — ghim biểu đồ đã xác thực phù hợp.')}</div>}</article>; }
