import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Download, FileText, Plus, Printer, Trash2 } from 'lucide-react';
import { CustomReportDocument, ManualGlossaryNote, ReportSection } from '../types';

const empty = (runId: string): CustomReportDocument => ({ run_id: runId, title: 'Custom Report', executive_summary: '', sections: [], pinned_artifacts: [], manual_glossary_notes: [], glossary: [], updated_at: '' });

export default function ReportComposer({ runId, report, onChange }: { runId: string; report: CustomReportDocument | null; onChange: (next: CustomReportDocument) => void }) {
  const [draft, setDraft] = useState<CustomReportDocument>(() => report ?? empty(runId));
  const [status, setStatus] = useState('');
  useEffect(() => setDraft(report ?? empty(runId)), [report, runId]);
  const save = async (next = draft) => { setDraft(next); setStatus('Saving…'); try { const response = await fetch(`/api/runs/${runId}/custom-report`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || 'Could not save report.'); onChange(body); setDraft(body); setStatus('Saved'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save report.'); } };
  const update = <K extends keyof CustomReportDocument>(key: K, value: CustomReportDocument[K]) => setDraft(current => ({ ...current, [key]: value }));
  const moveArtifact = (index: number, delta: number) => { const artifacts = [...draft.pinned_artifacts]; const target = index + delta; if (target < 0 || target >= artifacts.length) return; [artifacts[index], artifacts[target]] = [artifacts[target], artifacts[index]]; void save({ ...draft, pinned_artifacts: artifacts }); };
  const removeArtifact = (artifactId: string) => void save({ ...draft, pinned_artifacts: draft.pinned_artifacts.filter(item => item.artifact_id !== artifactId) });
  const addSection = () => update('sections', [...draft.sections, { section_id: crypto.randomUUID(), heading: 'New section', commentary: '', recommended_actions: [] }]);
  const updateSection = (index: number, patch: Partial<ReportSection>) => update('sections', draft.sections.map((item, i) => i === index ? { ...item, ...patch } : item));
  const addNote = () => update('manual_glossary_notes', [...draft.manual_glossary_notes, { note_id: crypto.randomUUID(), text: '' }]);
  const updateNote = (index: number, patch: Partial<ManualGlossaryNote>) => update('manual_glossary_notes', draft.manual_glossary_notes.map((item, i) => i === index ? { ...item, ...patch } : item));
  const exportReport = () => window.open(`/api/runs/${runId}/report`, '_blank', 'noopener,noreferrer');
  return <section className="report-composer"><header className="report-composer-header"><div><p className="section-eyebrow">Evidence-bound authored briefing</p><h1>Custom Report</h1><p>Author commentary is separate from validated server aggregates.</p></div><div className="report-actions"><span aria-live="polite" className={status.startsWith('Could') ? 'report-error' : ''}>{status}</span><button onClick={() => void save()}>Save</button><button onClick={exportReport}><Download size={15} /> Export HTML</button><button onClick={() => window.print()}><Printer size={15} /> Print / PDF</button></div></header>
    <div className="report-layout"><div className="report-editor">
      <label>Report title<input value={draft.title} maxLength={120} onChange={event => update('title', event.target.value)} onBlur={() => void save()} /></label>
      <label>Executive summary<textarea value={draft.executive_summary} maxLength={8000} rows={5} placeholder="Decision-ready summary, explicitly grounded in the evidence below." onChange={event => update('executive_summary', event.target.value)} onBlur={() => void save()} /></label>
      <div className="composer-heading"><h2>Sections and recommendations</h2><button onClick={addSection}><Plus size={15} /> Add section</button></div>
      {draft.sections.map((section, index) => <article className="report-section" key={section.section_id}><input aria-label="Section heading" value={section.heading} maxLength={160} onChange={event => updateSection(index, { heading: event.target.value })} onBlur={() => void save()} /><textarea aria-label="Section commentary" rows={4} value={section.commentary} maxLength={8000} placeholder="Commentary" onChange={event => updateSection(index, { commentary: event.target.value })} onBlur={() => void save()} /><textarea aria-label="Recommended actions" rows={2} value={section.recommended_actions.join('\n')} maxLength={4000} placeholder="Recommended actions (one per line)" onChange={event => updateSection(index, { recommended_actions: event.target.value.split('\n').map(item => item.trim()).filter(Boolean) })} onBlur={() => void save()} /><button className="danger-link" onClick={() => update('sections', draft.sections.filter(item => item.section_id !== section.section_id))}>Remove section</button></article>)}
      <div className="composer-heading"><h2>Pinned validated artifacts</h2><span>{draft.pinned_artifacts.length} pinned</span></div>
      {draft.pinned_artifacts.map((artifact, index) => <article className="report-artifact" key={artifact.artifact_id}><div className="artifact-controls"><button aria-label="Move artifact up" disabled={index === 0} onClick={() => moveArtifact(index, -1)}><ArrowUp size={15} /></button><button aria-label="Move artifact down" disabled={index === draft.pinned_artifacts.length - 1} onClick={() => moveArtifact(index, 1)}><ArrowDown size={15} /></button><button aria-label="Remove artifact" className="danger-link" onClick={() => removeArtifact(artifact.artifact_id)}><Trash2 size={15} /></button></div><p className="section-eyebrow">Validated artifact</p><h3>{artifact.title || `${artifact.chart.metric} by ${artifact.chart.dimension}`}</h3><p className="artifact-scope">{artifact.scope || `${artifact.chart.aggregation} · ${artifact.chart.chart_type}`}</p><div className="artifact-evidence"><strong>Evidence</strong>{artifact.evidence.map(item => <p key={item}>• {item}</p>)}</div>{artifact.warnings.map(item => <p className="artifact-warning" key={item}>{item}</p>)}<label>Author annotation<textarea rows={2} value={artifact.annotation} maxLength={2000} onChange={event => update('pinned_artifacts', draft.pinned_artifacts.map(item => item.artifact_id === artifact.artifact_id ? { ...item, annotation: event.target.value } : item))} onBlur={() => void save()} /></label></article>)}
      {!draft.pinned_artifacts.length && <div className="report-empty"><FileText size={30} /><p>Pin validated charts from Executive Hub or the analyst chat to add evidence.</p></div>}
    </div><aside className="report-glossary"><h2>Glossary</h2><p className="glossary-help">Validated entries derive from pinned artifacts.</p><ul>{draft.glossary.map(item => <li key={item.name}><strong>{item.label}</strong><span>{item.kind} · {item.description}</span></li>)}</ul><h3>Manual notes <small>Author-authored, not validated evidence</small></h3>{draft.manual_glossary_notes.map((note, index) => <div className="manual-note" key={note.note_id}><textarea aria-label="Manual glossary note" value={note.text} maxLength={1000} onChange={event => updateNote(index, { text: event.target.value })} onBlur={() => void save()} /><button aria-label="Remove manual note" onClick={() => update('manual_glossary_notes', draft.manual_glossary_notes.filter(item => item.note_id !== note.note_id))}><Trash2 size={14} /></button></div>)}<button onClick={addNote}><Plus size={15} /> Add manual note</button></aside></div>
  </section>;
}
