import { useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, Download, FileSpreadsheet, Info, ShieldCheck, TableProperties } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import AnalystPanel from './components/AnalystPanel';
import ChartPlanner from './components/ChartPlanner';
import DatasetSelector from './components/DatasetSelector';
import { ChartResult, DatasetProfile } from './types';

const KIND_LABEL: Record<string, string> = { time: '🕒 time', num: '📈 metric', cat: '🏷 dimension', id: '🔑 id', unknown: 'unknown' };

export default function App() {
  const [profile, setProfile] = useState<DatasetProfile | null>(null);
  const [charts, setCharts] = useState<ChartResult[]>([]);
  const numeric = useMemo(() => profile?.columns.filter((column) => column.kind === 'num') ?? [], [profile]);
  const category = useMemo(() => profile?.columns.filter((column) => column.kind === 'cat') ?? [], [profile]);
  const cardinality = useMemo(() => profile?.columns.slice(0, 8).map((column) => ({ name: column.name, distinct: column.distinct_count })) ?? [], [profile]);
  const selectProfile = (next: DatasetProfile) => { setProfile(next); setCharts([]); };
  const downloadReport = async () => { if (!profile || !charts.length) return; const response = await fetch(`/api/runs/${profile.run_id}/report`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: `${profile.file_name} report`, charts: charts.map(({ dimension, metric, aggregation, chart_type, secondary_dimension, filters }) => ({ dimension, metric, aggregation, chart_type, secondary_dimension, filters, limit: 12 })) }) }); if (!response.ok) { window.alert('Report generation failed. Please review the selected chart plan and try again.'); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'opendata-report.html'; link.click(); URL.revokeObjectURL(url); };
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white/90 backdrop-blur sticky top-0 z-10"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center gap-4"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-indigo-600 rounded-xl text-white flex items-center justify-center shadow-sm"><BarChart3 className="w-5 h-5" /></div><div><h1 className="text-xl font-bold tracking-tight">OpenData Report Workspace</h1><p className="text-xs text-slate-500">Guided analytics · Telegram-ready report runs</p></div></div><div className="hidden sm:flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="w-4 h-4 text-emerald-600" /> Server-side profiling · no raw data sent to AI</div></div></header>
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8"><div className="grid grid-cols-1 xl:grid-cols-12 gap-8"><div className="xl:col-span-5"><DatasetSelector profile={profile} onProfile={selectProfile} /></div><section className="xl:col-span-7 bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><div className="flex items-center gap-2 mb-2"><TableProperties className="w-5 h-5 text-indigo-600" /><h2 className="text-lg font-semibold">2. Dataset profile</h2></div>{profile ? <><p className="text-sm text-slate-500">{profile.usable_column_count} usable columns were classified from observed values. Review this before choosing filters or charts.</p><div className="grid grid-cols-3 gap-3 mt-5"><Metric label="Rows" value={profile.row_count.toLocaleString()} /><Metric label="Metrics" value={String(numeric.length)} /><Metric label="Dimensions" value={String(category.length)} /></div></> : <Empty text="Upload a CSV or XLSX to create the first report run." />}</section></div>
      {profile && <><section className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-6 border-b border-slate-100 flex justify-between gap-4"><div><h2 className="text-lg font-semibold">Column catalogue</h2><p className="text-sm text-slate-500 mt-1">These roles drive the upcoming filter and chart-plan steps.</p></div><span className="text-xs font-mono bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 h-fit">run {profile.run_id.slice(0, 8)}</span></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-xs uppercase tracking-wide"><tr><th className="text-left px-6 py-3">Column</th><th className="text-left px-6 py-3">Role</th><th className="text-right px-6 py-3">Distinct</th><th className="text-right px-6 py-3">Null</th><th className="text-left px-6 py-3">Description</th></tr></thead><tbody>{profile.columns.map((column) => <tr key={column.name} className="border-t border-slate-100"><td className="px-6 py-3 font-medium">{column.name}</td><td className="px-6 py-3 text-xs">{KIND_LABEL[column.kind]}</td><td className="px-6 py-3 text-right font-mono text-xs">{column.distinct_count.toLocaleString()}</td><td className="px-6 py-3 text-right font-mono text-xs">{(column.null_ratio * 100).toFixed(1)}%</td><td className="px-6 py-3 text-slate-500 text-xs max-w-md">{column.description}</td></tr>)}</tbody></table></div></section>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8"><section className="lg:col-span-7 bg-white rounded-2xl border border-slate-200 p-6 shadow-sm h-[380px]"><h2 className="text-lg font-semibold">Cardinality overview</h2><p className="text-xs text-slate-500 mt-1">A profile aid—not a business metric chart.</p><div className="h-[290px] mt-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={cardinality}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="name" fontSize={10} tick={{ fill: '#64748b' }} interval={0} angle={-25} textAnchor="end" height={70} /><YAxis fontSize={10} /><Tooltip /><Bar dataKey="distinct" name="Distinct values" fill="#4f46e5" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="lg:col-span-5 bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><h2 className="text-lg font-semibold">Quality notes</h2><p className="text-sm text-slate-500 mt-1">The report builder will surface these alongside its chart plan.</p><div className="mt-5 space-y-3">{profile.warnings.length ? profile.warnings.map((warning) => <div key={warning} className="flex gap-2 text-sm p-3 rounded-xl bg-amber-50 border border-amber-100 text-amber-900"><Info className="w-4 h-4 mt-0.5 shrink-0" />{warning}</div>) : <div className="flex gap-2 text-sm p-3 rounded-xl bg-emerald-50 border border-emerald-100 text-emerald-900"><CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" />No high-severity profile warnings detected.</div>}</div></section></div>
        <AnalystPanel profile={profile} onChart={(chart) => setCharts((current) => [...current, chart])} />
        <ChartPlanner profile={profile} onChart={(chart) => setCharts((current) => [...current, chart])} />
        {charts.length > 0 && <section className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><h2 className="text-lg font-semibold">4. Chart plan <span className="text-slate-400 font-normal">({charts.length}/12)</span></h2><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500 mt-1">Only server-calculated, validated aggregates are staged here.</p><button type="button" onClick={downloadReport} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700"><Download className="w-4 h-4" /> Download HTML report</button></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-5 mt-5">{charts.map((chart, index) => <ChartCard key={`${chart.title}-${index}`} chart={chart} />)}</div></section>}
        <section className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"><div className="flex items-center gap-2 mb-3"><FileSpreadsheet className="w-5 h-5 text-indigo-600" /><h2 className="text-lg font-semibold">Read-only preview</h2></div><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead><tr>{profile.columns.slice(0, 8).map((column) => <th className="text-left bg-slate-50 border-b border-slate-200 px-3 py-2 font-semibold text-slate-500" key={column.name}>{column.name}</th>)}</tr></thead><tbody>{profile.preview.slice(0, 8).map((row, index) => <tr className="border-b border-slate-100" key={index}>{profile.columns.slice(0, 8).map((column) => <td className="px-3 py-2 max-w-40 truncate" key={column.name}>{row[column.name] || '—'}</td>)}</tr>)}</tbody></table></div></section></>}
    </main></div>;
}
function ChartCard({ chart }: { chart: ChartResult }) { return <article className="border border-slate-200 rounded-xl p-4"><h3 className="font-semibold text-sm">{chart.title}</h3><p className="text-xs text-slate-500 mt-1">{chart.rows.length} ranked values · {chart.chart_type}</p><div className="h-48 mt-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart.rows}><XAxis dataKey="label" fontSize={10} /><YAxis fontSize={10} /><Tooltip /><Bar dataKey="value" fill="#4f46e5" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div>{chart.warnings.map((warning) => <p key={warning} className="text-xs text-amber-800 bg-amber-50 rounded-lg p-2 mt-2">{warning}</p>)}</article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 border border-slate-200 p-4"><p className="text-xs text-slate-500 uppercase tracking-wide">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="h-36 flex items-center justify-center text-sm text-slate-400">{text}</div>; }
