import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, BarChart3, CheckCircle2, Database, FileText, Globe2, LoaderCircle, Paperclip, Plus, Send, Sparkles, TableProperties, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import DatasetSelector from './components/DatasetSelector';
import { ChartResult, ChatResult, ClarificationOption, DatasetProfile, EDAResult, StarterView } from './types';
import { displayNumber, initialLanguage, Language, text } from './i18n';

type View = 'overview' | 'workspace' | 'eda';
type Message = { id: string; role: 'user' | 'assistant'; text: string; result?: ChatResult; pending?: string[]; selectionPending?: boolean; error?: string };
const compact = (value: number) => { const abs = Math.abs(value); if (abs >= 1e9) return `${(value / 1e9).toFixed(1)}B`; if (abs >= 1e6) return `${(value / 1e6).toFixed(1)}M`; if (abs >= 1e3) return `${(value / 1e3).toFixed(1)}K`; return value.toFixed(1); };

export default function App() {
  const [profile, setProfile] = useState<DatasetProfile | null>(null); const [profileLoading, setProfileLoading] = useState(false); const [view, setView] = useState<View>('overview');
  const [language, setLanguage] = useState<Language>(initialLanguage); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState('');
  const [busy, setBusy] = useState(false); const [artifacts, setArtifacts] = useState<Message[]>([]); const [starterViews, setStarterViews] = useState<StarterView[]>([]); const [eda, setEda] = useState<EDAResult | null>(null);
  const t = (key: Parameters<typeof text>[1]) => text(language, key);
  const attach = (next: DatasetProfile) => { setProfile(next); setMessages([{ id: 'intro', role: 'assistant', text: language === 'en' ? `Attached ${next.file_name}. You can review the schema while detailed data health is prepared.` : `Đã đính kèm ${next.file_name}. Anh có thể xem schema trong khi data health chi tiết đang được chuẩn bị.` }]); setArtifacts([]); setStarterViews([]); setEda(null); setView('overview'); };
  const refreshRun = async () => { if (!profile) return; const id = profile.run_id; setProfileLoading(true); try { const fullProfile = await fetch(`/api/runs/${id}/profile/status`).then(r => r.ok ? r.json() : null); if (fullProfile) setProfile(fullProfile as DatasetProfile); const [views, health] = await Promise.all([fetch(`/api/runs/${id}/starter-views`).then(r => r.ok ? r.json() : { proposals: [] }), fetch(`/api/runs/${id}/eda`).then(r => r.ok ? r.json() : null)]); setStarterViews(views.proposals ?? []); setEda(health); } finally { setProfileLoading(false); } };
  useEffect(() => { if (profile) void refreshRun(); }, [profile?.run_id]);
  const context = useMemo(() => messages.slice(-4).map(item => `${item.role}: ${item.text}`).join('\n').slice(-1000), [messages]);
  const requestResult = async (url: string, body: Record<string, unknown>, id: string) => {
    const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, language }) });
    const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'Unable to complete the analysis.'); return result as ChatResult;
  };
  const analyze = async (question: string) => { if (!profile || !question.trim() || busy) return; const id = crypto.randomUUID(); const progressId = `${id}-progress`; setMessages(items => [...items, { id, role: 'user', text: question }, { id: progressId, role: 'assistant', text: t('preparing'), pending: [t('preparing')] }]); setBusy(true);
    try { const response = await fetch(`/api/runs/${profile.run_id}/chat/stream`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: question, context, language }) }); if (!response.ok || !response.body) throw new Error('Unable to start analysis.'); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; let stages: string[] = [t('preparing')]; let finalResult: ChatResult | undefined;
      const consume = (block: string) => { const event = block.match(/^event: (.+)$/m)?.[1]; const raw = block.match(/^data: (.+)$/m)?.[1]; if (!event || !raw) return; const payload = JSON.parse(raw) as { label: string; response?: ChatResult }; if (event === 'completed' || event === 'clarification') finalResult = payload.response; else if (event === 'error') throw new Error(payload.label); else { stages = [...stages, payload.label].filter((v, i, list) => list.indexOf(v) === i); setMessages(items => items.map(item => item.id === progressId ? { ...item, pending: stages } : item)); } };
      for (;;) { const next = await reader.read(); if (next.done) break; buffer += decoder.decode(next.value, { stream: true }); const blocks = buffer.split('\n\n'); buffer = blocks.pop() ?? ''; blocks.forEach(consume); } if (!finalResult) throw new Error('Analysis did not return a complete result.'); setMessages(items => [...items.filter(item => item.id !== progressId), { id: `${id}-result`, role: 'assistant', text: finalResult!.answer, result: finalResult }]);
    } catch (error) { setMessages(items => [...items.filter(item => item.id !== progressId), { id: `${id}-error`, role: 'assistant', text: error instanceof Error ? error.message : 'Unable to analyze data.' }]); } finally { setBusy(false); } };
  const choose = async (message: Message, option: ClarificationOption) => { if (!profile || message.selectionPending) return; setMessages(items => items.map(item => item.id === message.id ? { ...item, selectionPending: true, error: undefined } : item)); try { const result = await requestResult(`/api/runs/${profile.run_id}/semantic-selection`, { column: option.column, role: option.role }, message.id); setMessages(items => [...items.map(item => item.id === message.id ? { ...item, selectionPending: false, text: `${t('selected')}: ${option.label} · ${t('userConfirmed')}`, result: undefined } : item), { id: crypto.randomUUID(), role: 'assistant', text: result.answer, result }]); } catch (e) { setMessages(items => items.map(item => item.id === message.id ? { ...item, selectionPending: false, error: e instanceof Error ? e.message : 'Unable to save selection.' } : item)); } };
  const send = (event: FormEvent) => { event.preventDefault(); const question = draft.trim(); setDraft(''); void analyze(question); }; const generate = (item: StarterView) => void analyze(item.question ?? item.title); const pin = (message: Message) => setArtifacts(items => items.some(item => item.id === message.id) ? items : [...items, message]);
  const stats = profile ? [[displayNumber(profile.row_count, language), t('rowsLabel')], [String(profile.column_count), t('columnsLabel')], [String(profile.usable_column_count), t('analyzed')], [profile.profile_status === 'sampled' ? '…' : '✓', profile.profile_status === 'sampled' ? t('profilePreparing') : t('profileReady')]] : [];
  return <div className="min-h-screen bg-slate-100 text-slate-900"><header className="app-header"><div className="app-header-inner"><div className="flex items-center gap-2"><span className="w-9 h-9 grid place-items-center rounded-xl bg-indigo-600 text-white shadow-sm"><Sparkles className="w-4 h-4" /></span><div><b className="font-display block leading-4">OpenData</b><span className="text-[11px] text-slate-400">{t('workspace')}</span></div></div>{profile && <nav className="app-tabs"><button onClick={() => setView('overview')} className={view === 'overview' ? 'active' : ''}>{t('overview')}</button><button onClick={() => setView('workspace')} className={view === 'workspace' ? 'active' : ''}>{t('reportChat')}</button><button onClick={() => setView('eda')} className={view === 'eda' ? 'active' : ''}>{t('eda')}</button></nav>}<label className="locale-select"><Globe2 className="w-3.5 h-3.5" /><span className="sr-only">{t('language')}</span><select value={language} onChange={event => { const next = event.target.value as Language; setLanguage(next); localStorage.setItem('opendata.locale', next); }}><option value="en">English</option><option value="vi">Tiếng Việt</option></select></label></div></header>
  {!profile ? <main className="max-w-2xl mx-auto px-4 pt-14"><div className="text-center mb-8"><h1 className="font-display text-3xl font-bold">{t('attachTitle')}</h1><p className="text-slate-500 mt-3">{t('attachSubtitle')}</p></div><DatasetSelector profile={null} language={language} onProfile={attach} /></main> : <main className="max-w-[1500px] mx-auto p-3 lg:p-5">{view === 'overview' ? <section className="space-y-4"><DatasetBar profile={profile} onRemove={() => setProfile(null)} language={language} /><div className="preparing-strip">{profileLoading && <><LoaderCircle className="w-3.5 h-3.5 animate-spin" /> {t('profilePreparing')}</>}</div><div><p className="section-eyebrow">{t('dataset')}</p><h1 className="font-display text-2xl font-bold">{t('overviewTitle')}</h1><p className="text-sm text-slate-500 mt-1">{t('overviewSub')}</p></div><div className="kpi-grid">{stats.map(([value, label]) => <div className="kpi-card" key={label}><p>{label}</p><b>{value}</b></div>)}</div><OverviewCards views={starterViews} busy={busy} onGenerate={generate} language={language} /></section> : view === 'eda' ? <EDATab eda={eda} profile={profile} language={language} /> : <div className="workspace-grid"><section className="min-w-0 space-y-4"><DatasetBar profile={profile} onRemove={() => setProfile(null)} language={language} /><ReportCanvas artifacts={artifacts} starterViews={starterViews} onGenerate={generate} busy={busy} language={language} onRemove={id => setArtifacts(items => items.filter(item => item.id !== id))} /></section><aside className="chat-panel"><div className="px-4 py-3 border-b bg-white flex items-center gap-2"><Activity className="w-4 h-4 text-indigo-600" /><b className="text-sm">{t('copilot')}</b><span className="ml-auto text-xs text-slate-400">{t('runScoped')}</span></div><div className="flex-1 overflow-y-auto p-3 space-y-3"><ChatMessages messages={messages} onPin={pin} onChoose={choose} language={language} /><Suggestions views={starterViews} onGenerate={generate} busy={busy} language={language} /></div><form onSubmit={send} className="border-t p-3 bg-white"><div className="rounded-xl border bg-slate-50 focus-within:ring-2 focus-within:ring-indigo-200 p-2 flex gap-2"><textarea rows={2} value={draft} onChange={e => setDraft(e.target.value)} placeholder={t('ask')} className="flex-1 resize-none bg-transparent text-sm outline-none" /><button aria-label={t('ask')} disabled={busy || !draft.trim()} className="self-end p-2 rounded-lg bg-indigo-600 disabled:bg-slate-300 text-white"><Send className="w-4 h-4" /></button></div><p className="text-[11px] text-slate-400 mt-2">{t('askHelp')}</p></form></aside></div>}</main>}</div>;
}
function DatasetBar({ profile, onRemove, language }: { profile: DatasetProfile; onRemove: () => void; language: Language }) { return <div className="dataset-bar"><Paperclip className="w-4 h-4 text-indigo-600" /><b className="truncate">{profile.file_name}</b><span>{displayNumber(profile.row_count, language)} {text(language, 'rows')} · {profile.column_count} {text(language, 'columns')}</span><span className={`status-pill ${profile.profile_status === 'sampled' ? 'pending' : ''}`}>{profile.profile_status === 'sampled' ? text(language, 'profilePreparing') : text(language, 'profileReady')}</span><button onClick={onRemove} className="ml-auto p-1 text-slate-400 hover:text-slate-700" aria-label="Remove dataset"><X className="w-4 h-4" /></button></div>; }
function OverviewCards({ views, busy, onGenerate, language }: { views: StarterView[]; busy: boolean; onGenerate: (item: StarterView) => void; language: Language }) { return <div className="rounded-2xl border bg-white shadow-sm p-5"><div className="flex items-start gap-3"><span className="grid place-items-center h-9 w-9 rounded-xl bg-indigo-50 text-indigo-600"><BarChart3 className="w-5 h-5" /></span><div><h2 className="font-semibold">{text(language, 'starter')}</h2><p className="text-sm text-slate-500 mt-1">{text(language, 'starterSub')}</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-5">{views.slice(0, 5).map(item => <button key={item.id} disabled={busy} onClick={() => onGenerate(item)} className="starter-card"><p>{item.title}</p><span>{item.rationale}</span><em>{text(language, 'generate')} <ArrowUpRight className="w-3 h-3" /></em></button>)}</div>{!views.length && <div className="flex items-center gap-2 text-sm text-slate-500 mt-5"><LoaderCircle className="w-4 h-4 animate-spin" />{text(language, 'chartPending')}</div>}</div>; }
function ReportCanvas({ artifacts, starterViews, onGenerate, onRemove, busy, language }: { artifacts: Message[]; starterViews: StarterView[]; onGenerate: (item: StarterView) => void; onRemove: (id: string) => void; busy: boolean; language: Language }) { return <div className="rounded-2xl border bg-white shadow-sm min-h-[560px]"><div className="p-5 border-b flex items-start justify-between gap-4"><div><p className="section-eyebrow">{text(language, 'reportChat')}</p><h1 className="font-display text-xl font-bold mt-1">{text(language, 'reportTitle')}</h1><p className="text-sm text-slate-500 mt-1">{text(language, 'reportSub')}</p></div><FileText className="w-5 h-5 text-slate-400" /></div>{artifacts.length ? <div className="p-5 space-y-5">{artifacts.map(item => <AnalysisArtifact key={item.id} message={item} inReport language={language} onRemove={() => onRemove(item.id)} />)}</div> : <div className="p-5"><OverviewCards views={starterViews} busy={busy} onGenerate={onGenerate} language={language} /></div>}</div>; }
function ChatMessages({ messages, onPin, onChoose, language }: { messages: Message[]; onPin: (message: Message) => void; onChoose: (message: Message, option: ClarificationOption) => void; language: Language }) { return <>{messages.map(message => <article key={message.id} className={message.role === 'user' ? 'ml-8 rounded-2xl bg-indigo-600 text-white px-3 py-2.5 text-sm' : 'rounded-xl border bg-white p-3 text-sm shadow-sm'}>{message.pending ? <Progress stages={message.pending} language={language} /> : <><p className="leading-6">{message.text}</p>{message.result?.chart && <AnalysisArtifact message={message} compact language={language} onPin={() => onPin(message)} />}{message.result?.proposals?.length ? <div className="mt-3 space-y-2">{message.result.proposals.map(option => <button key={option.id} className="proposal-row" onClick={() => undefined}><b>{option.title}</b><span>{option.rationale}</span></button>)}</div> : null}{message.result?.clarification_options?.length ? <div className="mt-3"><p className="text-xs text-slate-500 mb-2">{text(language, 'suggestions')}</p><div className="flex flex-wrap gap-2">{message.result.clarification_options.map(option => <button key={option.column} type="button" disabled={message.selectionPending} onClick={() => onChoose(message, option)} title={option.reason} aria-label={`${option.label}: ${option.reason}`} className="clarification-chip">{message.selectionPending ? <LoaderCircle className="w-3 h-3 animate-spin" /> : <CheckCircle2 className="w-3 h-3" />}{option.label}</button>)}</div>{message.error && <p className="mt-2 text-xs text-rose-600">{message.error}</p>}</div> : null}</>}</article>)}</>; }
function Progress({ stages, language }: { stages: string[]; language: Language }) { return <div><div className="flex items-center gap-2 text-indigo-700 font-medium"><LoaderCircle className="w-4 h-4 animate-spin" /> {text(language, 'analyzing')}</div><div className="mt-3 space-y-2">{stages.map((stage, i) => <p key={stage} className={`text-xs flex gap-2 ${i === stages.length - 1 ? 'text-slate-700' : 'text-slate-400'}`}><span>{i < stages.length - 1 ? '✓' : '•'}</span>{stage}</p>)}</div></div>; }
function AnalysisArtifact({ message, compact: dense, inReport, onPin, onRemove, language }: { message: Message; compact?: boolean; inReport?: boolean; onPin?: () => void; onRemove?: () => void; language: Language }) { const result = message.result!; const chart = result.chart!; return <section className={dense ? 'mt-3 border-t pt-3' : 'rounded-xl border p-4'}><div className="flex items-start justify-between gap-3"><div><p className="section-eyebrow">{inReport ? 'Verified report artifact' : result.planner === 'llm' ? 'LLM plan · Validated aggregate' : 'Validated aggregate'}</p><h3 className="font-semibold mt-1">{chart.title}</h3></div>{onRemove && <button onClick={onRemove} className="text-xs text-slate-400 hover:text-rose-600">{text(language, 'remove')}</button>}</div><div className="mt-3 rounded-lg bg-emerald-50 border border-emerald-100 p-3"><p className="text-xs uppercase text-emerald-700 font-semibold">{text(language, 'keyFinding')}</p><p className="font-medium text-slate-800 mt-1">{result.insight}</p>{chart.evidence?.map(item => <p className="text-xs text-slate-600 mt-1" key={item}>• {item}</p>)}</div><div className={dense ? 'h-48 mt-3' : 'h-72 mt-4'}><Chart chart={chart} /></div><p className="text-xs text-slate-500 mt-3">{result.scope}</p>{result.caveats.map(note => <p key={note} className="text-xs text-amber-800 bg-amber-50 mt-3 p-2 rounded">{note}</p>)}{onPin && <button onClick={onPin} className="mt-3 text-xs font-medium text-indigo-700 inline-flex gap-1"><Plus className="w-3.5 h-3.5" /> {text(language, 'addReport')}</button>}</section>; }
function Chart({ chart }: { chart: ChartResult }) { const C = chart.chart_type === 'line' ? LineChart : BarChart; return <ResponsiveContainer width="100%" height="100%"><C data={chart.rows}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="display_label" fontSize={10} interval="preserveStartEnd" /><YAxis tickFormatter={compact} fontSize={10} width={48} /><Tooltip labelFormatter={(_, p) => p[0]?.payload?.display_label ?? ''} formatter={(v: number) => compact(v)} />{chart.chart_type === 'line' ? <Line type="monotone" dataKey="value" stroke="#4f46e5" strokeWidth={2} dot={{ r: 3 }} /> : <Bar dataKey="value" fill="#4f46e5" radius={[4, 4, 0, 0]} />}</C></ResponsiveContainer>; }
function Suggestions({ views, onGenerate, busy, language }: { views: StarterView[]; onGenerate: (view: StarterView) => void; busy: boolean; language: Language }) { return views.length ? <div className="pt-1"><p className="section-eyebrow mb-2">{text(language, 'starter')}</p><div className="flex flex-wrap gap-2">{views.slice(0, 3).map(view => <button key={view.id} disabled={busy} onClick={() => onGenerate(view)} className="text-xs text-left rounded-lg bg-slate-100 hover:bg-indigo-50 hover:text-indigo-700 px-2 py-1.5">{view.title}</button>)}</div></div> : null; }
function EDATab({ eda, profile, language }: { eda: EDAResult | null; profile: DatasetProfile; language: Language }) { return <section className="max-w-6xl mx-auto space-y-4"><DatasetBar profile={profile} onRemove={() => undefined} language={language} /><div className="rounded-2xl bg-white border p-5"><div className="flex gap-2 items-center"><TableProperties className="w-5 h-5 text-indigo-600" /><div><h1 className="font-display text-xl font-bold">{text(language, 'healthTitle')}</h1><p className="text-sm text-slate-500">{text(language, 'healthSub')}</p></div></div>{!eda ? <div className="flex gap-2 text-sm text-slate-500 mt-5"><LoaderCircle className="w-4 h-4 animate-spin" /> {text(language, 'profilePreparing')}</div> : <><div className="kpi-grid mt-5">{[[displayNumber(eda.coverage.row_count, language), text(language, 'rowsLabel')], [String(eda.coverage.column_count), text(language, 'columnsLabel')], [String(eda.coverage.analyzed_column_count), text(language, 'analyzed')], [String(eda.coverage.suppressed_sensitive_column_count), text(language, 'hidden')]].map(([value, label]) => <div key={label} className="kpi-card"><p>{label}</p><b>{value}</b></div>)}</div><div className="grid md:grid-cols-2 gap-4 mt-5">{eda.columns.map(column => <div key={column.name} className="rounded-xl border p-4"><p className="font-medium text-sm">{column.name} <span className="text-xs text-slate-400">{column.kind}</span></p><p className="text-xs text-slate-500 mt-2">{column.quality.non_null_count.toLocaleString()} non-null · {column.quality.distinct_count.toLocaleString()} distinct · {(column.quality.null_ratio * 100).toFixed(1)}% null</p>{column.numeric_summary && <p className="text-xs text-slate-600 mt-2">Min {compact(column.numeric_summary.min ?? 0)} · Mean {compact(column.numeric_summary.mean ?? 0)} · Max {compact(column.numeric_summary.max ?? 0)}</p>}{column.time_coverage && <p className="text-xs text-slate-600 mt-2">{column.time_coverage.start?.slice(0, 10) ?? '—'} → {column.time_coverage.end?.slice(0, 10) ?? '—'}</p>}{column.top_categories && <div className="mt-2 flex flex-wrap gap-1">{column.top_categories.slice(0, 4).map(item => <span key={item.value} className="text-[11px] bg-slate-100 px-1.5 py-0.5 rounded">{item.value} · {item.count}</span>)}</div>}</div>)}</div></>}</div></section>; }
