import { FormEvent, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUp, BarChart3, Database, FileText, LoaderCircle, Paperclip, Send, Sparkles, TableProperties, X } from 'lucide-react';
import DatasetSelector from './components/DatasetSelector';
import { ChartResult, DatasetProfile } from './types';

type Tab = 'chat' | 'eda' | 'report';
type Message = { role: 'user' | 'assistant'; text: string; insight?: string; scope?: string; chart?: ChartResult; caveats?: string[] };
const compact = (value: number) => { const abs = Math.abs(value); if (abs >= 1e9) return `${(value / 1e9).toFixed(1)}B`; if (abs >= 1e6) return `${(value / 1e6).toFixed(1)}M`; if (abs >= 1e3) return `${(value / 1e3).toFixed(1)}K`; return value.toFixed(1); };

export default function App() {
  const [profile, setProfile] = useState<DatasetProfile | null>(null);
  const [tab, setTab] = useState<Tab>('chat');
  const [messages, setMessages] = useState<Message[]>([]);
  const [draft, setDraft] = useState('');
  const [loading, setLoading] = useState(false);
  const [pinned, setPinned] = useState<Message[]>([]);
  const attach = (next: DatasetProfile) => { setProfile(next); setMessages([{ role: 'assistant', text: `Đã attach ${next.file_name}. Anh có thể hỏi về xu hướng, so sánh, phân khúc hoặc biến động trong dataset này.` }]); setPinned([]); setTab('chat'); };
  const send = async (event: FormEvent) => { event.preventDefault(); if (!profile || !draft.trim() || loading) return; const question = draft.trim(); const context = messages.slice(-4).map((item) => `${item.role}: ${item.text}`).join('\n').slice(-1000); setDraft(''); setMessages((items) => [...items, { role: 'user', text: question }]); setLoading(true); try { const response = await fetch(`/api/runs/${profile.run_id}/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: question, context }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Không thể phân tích dữ liệu.'); setMessages((items) => [...items, { role: 'assistant', text: data.answer, insight: data.insight, scope: data.scope, chart: data.chart, caveats: data.caveats }]); } catch (error) { setMessages((items) => [...items, { role: 'assistant', text: error instanceof Error ? error.message : 'Không thể phân tích dữ liệu.' }]); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b bg-white sticky top-0 z-10"><div className="max-w-6xl mx-auto h-16 px-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className="w-8 h-8 grid place-items-center rounded-lg bg-indigo-600 text-white"><Sparkles className="w-4 h-4" /></span><b>OpenData</b><span className="text-slate-400 text-sm">Data chat</span></div>{profile && <div className="hidden sm:flex rounded-lg bg-slate-100 p-1">{(['chat', 'eda', 'report'] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`px-3 py-1.5 rounded-md text-sm capitalize ${tab === item ? 'bg-white shadow text-indigo-700' : 'text-slate-500'}`}>{item}</button>)}</div>}</div></header><main className="max-w-6xl mx-auto px-4 py-6">{!profile ? <div className="max-w-2xl mx-auto pt-16"><div className="text-center mb-8"><h1 className="text-3xl font-bold">Ask your data anything</h1><p className="text-slate-500 mt-3">Attach a CSV, XLSX, or registered source. Analysis remains read-only and evidence-bound.</p></div><DatasetSelector profile={null} onProfile={attach} /></div> : <><div className="flex items-center gap-2 border rounded-xl bg-white px-3 py-2 mb-5 text-sm"><Paperclip className="w-4 h-4 text-indigo-600" /><b className="truncate">{profile.file_name}</b><span className="text-slate-500">{profile.row_count.toLocaleString()} rows · {profile.column_count} columns</span><button onClick={() => setProfile(null)} className="ml-auto"><X className="w-4 h-4 text-slate-400" /></button></div>{tab === 'chat' && <Chat messages={messages} loading={loading} onPin={(m) => setPinned((items) => items.includes(m) ? items : [...items, m])} />}{tab === 'eda' && <EDA profile={profile} />}{tab === 'report' && <Report items={pinned} />}{tab === 'chat' && <form onSubmit={send} className="sticky bottom-3 max-w-3xl mx-auto mt-6 rounded-2xl bg-white border shadow-lg p-2 flex gap-2"><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Ask about this dataset…" className="flex-1 outline-none px-3 text-sm" /><button disabled={loading} className="rounded-xl bg-indigo-600 text-white p-2 disabled:opacity-50">{loading ? <LoaderCircle className="w-5 h-5 animate-spin" /> : <ArrowUp className="w-5 h-5" />}</button></form>}</>}</main></div>;
}
function Chat({ messages, loading, onPin }: { messages: Message[]; loading: boolean; onPin: (message: Message) => void }) { return <section className="max-w-3xl mx-auto space-y-5">{messages.map((message, index) => <article key={index} className={message.role === 'user' ? 'ml-auto max-w-[80%] rounded-2xl bg-indigo-600 text-white px-4 py-3 text-sm' : 'rounded-2xl bg-white border p-5'}><p className="text-sm leading-6">{message.text}</p>{message.chart && <><div className="mt-4 border-t pt-4"><p className="text-xs uppercase tracking-wide text-slate-400">{message.scope}</p><p className="font-medium text-slate-800 mt-2">{message.insight}</p><div className="h-60 mt-3"><Chart chart={message.chart} /></div><div className="overflow-x-auto mt-3"><table className="text-xs min-w-full"><tbody>{message.chart.rows.slice(0, 6).map((row) => <tr key={String(row.label)} className="border-t"><td className="py-2 pr-5">{row.label}</td><td className="py-2 text-right font-medium">{compact(Number(row.value))}</td></tr>)}</tbody></table></div></div><button onClick={() => onPin(message)} className="mt-4 text-xs font-medium text-indigo-700 inline-flex gap-1"><FileText className="w-3.5 h-3.5" /> Pin to report</button></>}{message.caveats?.map((note) => <p key={note} className="text-xs text-amber-800 bg-amber-50 mt-3 p-2 rounded">{note}</p>)}</article>)}{loading && <div className="text-sm text-slate-500 flex gap-2"><LoaderCircle className="animate-spin w-4 h-4" /> Analyzing the attached data…</div>}</section>; }
function Chart({ chart }: { chart: ChartResult }) { const C = chart.chart_type === 'line' ? LineChart : BarChart; return <ResponsiveContainer width="100%" height="100%"><C data={chart.rows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" fontSize={10} /><YAxis tickFormatter={compact} fontSize={10} /><Tooltip formatter={(v: number) => compact(v)} /><>{chart.chart_type === 'line' ? <Line type="monotone" dataKey="value" stroke="#4f46e5" strokeWidth={2} /> : <Bar dataKey="value" fill="#4f46e5" radius={[4, 4, 0, 0]} />}</></C></ResponsiveContainer>; }
function EDA({ profile }: { profile: DatasetProfile }) { return <section className="bg-white border rounded-2xl p-6"><div className="flex gap-2 items-center"><TableProperties className="w-5 h-5 text-indigo-600" /><h2 className="font-semibold">EDA & dataset metadata</h2></div><p className="text-sm text-slate-500 mt-2">Profile and inferred types. Add business definitions in the next iteration through a data dictionary or dataset context.</p><div className="overflow-x-auto mt-5"><table className="min-w-full text-sm"><thead className="text-left text-xs text-slate-500 border-b"><tr><th className="py-2">Column</th><th>Type</th><th>Distinct</th><th>Null</th><th>Description</th></tr></thead><tbody>{profile.columns.map((c) => <tr key={c.name} className="border-b"><td className="py-3 font-medium">{c.name}</td><td>{c.kind}</td><td>{c.distinct_count.toLocaleString()}</td><td>{(c.null_ratio * 100).toFixed(1)}%</td><td className="text-slate-500">{c.description}</td></tr>)}</tbody></table></div></section>; }
function Report({ items }: { items: Message[] }) { return <section className="max-w-3xl mx-auto"><h2 className="text-xl font-semibold mb-2">Report</h2><p className="text-sm text-slate-500 mb-5">Pinned analysis artifacts become the evidence-bound report.</p>{items.length ? <div className="space-y-4">{items.map((item, i) => <article key={i} className="bg-white border rounded-2xl p-5"><h3 className="font-medium">{item.text}</h3><p className="text-sm text-slate-600 mt-2">{item.insight}</p>{item.chart && <div className="h-56 mt-3"><Chart chart={item.chart} /></div>}</article>)}</div> : <div className="rounded-2xl border bg-white p-8 text-slate-500 text-sm">Pin an analysis from Chat to begin a report.</div>}</section>; }
