export type Language = 'en' | 'vi';

export const DEFAULT_LANGUAGE: Language = 'en';

const copy = {
  en: {
    workspace: 'Analytical workspace', overview: 'Executive Hub', deepDive: 'Deep Dive Lab', reportTitle: 'Custom Report', navigation: 'Workspace navigation',
    attachTitle: 'Ask your data anything', attachSubtitle: 'Attach a dataset, then review verified analysis with a data copilot.', upload: 'Upload a CSV or XLSX', uploadHint: 'Up to 100 MB / 600,000 rows. Your data stays on the server and is never sent as raw rows to an AI.',
    uploadDrop: 'Drag and drop a CSV, or', browse: 'browse', uploadInvalid: 'Upload a CSV or XLSX file. Legacy XLS is not supported.', uploadRejected: 'The profiling service rejected this file.', uploadFailed: 'Upload failed. Check that the report API is running.',
    dataset: 'Dataset', rows: 'rows', columns: 'columns', profileReady: 'Data profile ready', profilePreparing: 'Preparing detailed data health', removeDataset: 'Remove dataset',
    overviewTitle: 'Executive Hub', overviewSub: 'Validated aggregate analysis from the active dataset.', overviewGenerated: 'Generated executive overview', overviewGuardrail: 'All charts are validated server aggregates.',
    copilot: 'Data Copilot', runScoped: 'Run-scoped', openChat: 'Open Data Copilot', closeChat: 'Close Data Copilot', ask: 'Ask about this dataset…', askHelp: 'Enter sends · Shift+Enter adds a line. I will ask for confirmation when a metric, time field, or business meaning is unclear.',
    starter: 'Suggested starting views', starterSub: 'Based on schema and data quality—not raw rows sent to an AI.', generate: 'Generate', addReport: 'Add to report', remove: 'Remove', keyFinding: 'Key finding', evidence: 'Evidence', scope: 'Scope', caveat: 'Caveat', suggestions: 'Suggested analyses',
    analyzing: 'Working with your data', preparing: 'Preparing analysis…', chartPending: 'Preparing starter views from the data profile…', selected: 'Selected', userConfirmed: 'User-confirmed for this dataset', language: 'Language', english: 'English', vietnamese: 'Tiếng Việt',
    chartPlayground: 'Chart playground', chartPlaygroundHelp: 'Server-validated aggregate only. Build adds the result to this Executive canvas.', dimension: 'Dimension', metric: 'Metric', aggregation: 'Aggregation', chartType: 'Chart type', groupBy: 'Group by (optional)', limit: 'Limit', noGroup: 'No group', sum: 'Sum', average: 'Average', countRecords: 'Count records', bar: 'Bar', line: 'Line', area: 'Area', buildChart: 'Build chart', addFilter: 'Add filter', filterValue: 'Filter value', noFilters: 'No filters', validatedScope: 'Validated scope', updating: 'Updating', primaryTrend: 'Primary trend', ranking: 'Ranking / distribution', customChart: 'Custom chart', group: 'Group', none: 'None', type: 'Type', viewRecords: 'View matching records', chartNoRows: 'No aggregate rows match this validated scope.', chartConfigure: 'Configure this chart to request a server-validated aggregate.', chartNeedsFields: 'A chart needs a category or time dimension and a numeric metric.', chartRejected: 'Chart request was rejected.', chartFailed: 'Could not build chart.', chartUpdateFailed: 'Could not update chart.',
    deepDiveTitle: 'Deep Dive Lab', deepDiveEyebrow: 'Safe raw data explorer', deepDiveHelp: 'Search, filter, sort, and export only presentation-safe fields from this run.', exportFiltered: 'Export filtered CSV', preparingCsv: 'Preparing CSV…', sourceChart: 'Source chart', groupedBy: 'grouped by', sourceScopeHelp: 'Its validated filters are pre-applied below and rechecked by the data API.', searchData: 'Search visible data…', searchVisibleData: 'Search visible data', loadingResults: 'Loading results', matchingRows: 'matching rows', columnsVisible: 'Columns', filters: 'Filters', validatedServer: 'Validated server-side', filterField: 'Filter field', filterOperator: 'Filter operator', filterValueLabel: 'Filter value', number: 'Number', value: 'Value', clearAll: 'Clear all', loadingData: 'Loading safe data…', noMatchingRows: 'No matching rows', noMatchingHelp: 'Try changing the search or removing one of the filters.', clearExplorer: 'Clear explorer', pageOf: 'Page {page} of {count}', previous: 'Previous', next: 'Next', sortBy: 'Sort by {column}', numericRequired: 'Numeric comparisons require a number.', duplicateFilter: 'That filter is already applied.', dataLoadFailed: 'Could not load raw data.', exportFailed: 'Could not export filtered data.',
    dataHealthContext: 'Data health context', safeFieldsAnalyzed: 'safe fields analyzed', sensitiveExcluded: 'sensitive fields excluded', safeFields: 'Safe fields', sensitiveFieldsHidden: 'Sensitive fields hidden', fieldsMissing: 'Fields >10% missing', distinct: 'distinct', null: 'null', preparingHealth: 'Preparing data health context…',
    reportEyebrow: 'Evidence-bound authored briefing', reportSub: 'Author commentary is separate from validated server aggregates.', save: 'Save', saving: 'Saving…', saved: 'Saved', exportHtml: 'Export HTML', printPdf: 'Print / PDF', reportTitleLabel: 'Report title', executiveSummary: 'Executive summary', reportSummaryPlaceholder: 'Decision-ready summary, explicitly grounded in the evidence below.', sectionsRecommendations: 'Sections and recommendations', addSection: 'Add section', sectionHeading: 'Section heading', sectionCommentary: 'Section commentary', commentary: 'Commentary', recommendedActions: 'Recommended actions', recommendedActionsPlaceholder: 'Recommended actions (one per line)', removeSection: 'Remove section', pinnedArtifacts: 'Pinned validated artifacts', pinned: 'pinned', moveUp: 'Move artifact up', moveDown: 'Move artifact down', removeArtifact: 'Remove artifact', validatedArtifact: 'Validated artifact', authorAnnotation: 'Author annotation', reportEmpty: 'Pin validated charts from Executive Hub or the analyst chat to add evidence.', glossary: 'Glossary', glossaryHelp: 'Validated entries derive from pinned artifacts.', manualNotes: 'Manual notes', manualNotesHelp: 'Author-authored, not validated evidence', manualNote: 'Manual glossary note', removeManualNote: 'Remove manual note', addManualNote: 'Add manual note', reportSaveFailed: 'Could not save report.',
    healthTitle: 'Data health & EDA', healthSub: 'Coverage, quality, cardinality, and bounded distribution facts. Sensitive values are excluded.', rowsLabel: 'Rows', columnsLabel: 'Columns', analyzed: 'Analyzed', hidden: 'Sensitive fields hidden', label: 'Label', secondaryGroup: 'Secondary group',
  },
  vi: {
    workspace: 'Không gian phân tích', overview: 'Tổng quan điều hành', deepDive: 'Khám phá chuyên sâu', reportTitle: 'Báo cáo tùy chỉnh', navigation: 'Điều hướng không gian làm việc',
    attachTitle: 'Hỏi mọi điều về dữ liệu của bạn', attachSubtitle: 'Đính kèm dataset để xem phân tích đã được kiểm chứng cùng data copilot.', upload: 'Tải lên CSV hoặc XLSX', uploadHint: 'Tối đa 100 MB / 600.000 dòng. Dữ liệu nằm trên server và không gửi raw rows vào AI.',
    uploadDrop: 'Kéo thả CSV, hoặc', browse: 'chọn tệp', uploadInvalid: 'Hãy tải lên tệp CSV hoặc XLSX. XLS cũ không được hỗ trợ.', uploadRejected: 'Dịch vụ lập hồ sơ đã từ chối tệp này.', uploadFailed: 'Tải lên thất bại. Hãy kiểm tra Report API đang chạy.',
    dataset: 'Dataset', rows: 'dòng', columns: 'cột', profileReady: 'Profile dữ liệu sẵn sàng', profilePreparing: 'Đang chuẩn bị data health chi tiết', removeDataset: 'Gỡ dataset',
    overviewTitle: 'Tổng quan điều hành', overviewSub: 'Phân tích aggregate đã xác thực từ dataset đang chọn.', overviewGenerated: 'Tổng quan điều hành đã tạo', overviewGuardrail: 'Mọi chart đều là aggregate đã xác thực trên server.',
    copilot: 'Data Copilot', runScoped: 'Theo run', openChat: 'Mở Data Copilot', closeChat: 'Đóng Data Copilot', ask: 'Hỏi về dataset này…', askHelp: 'Enter để gửi · Shift+Enter để xuống dòng. Em sẽ hỏi lại khi metric, trường thời gian hoặc business meaning chưa rõ.',
    starter: 'Góc nhìn gợi ý', starterSub: 'Dựa vào schema và data quality — không gửi raw rows vào AI.', generate: 'Tạo', addReport: 'Thêm vào báo cáo', remove: 'Xóa', keyFinding: 'Phát hiện chính', evidence: 'Bằng chứng', scope: 'Phạm vi', caveat: 'Lưu ý', suggestions: 'Gợi ý phân tích',
    analyzing: 'Đang làm việc với dữ liệu', preparing: 'Đang chuẩn bị phân tích…', chartPending: 'Đang tạo starter views từ profile dữ liệu…', selected: 'Đã chọn', userConfirmed: 'Đã xác nhận cho dataset này', language: 'Ngôn ngữ', english: 'English', vietnamese: 'Tiếng Việt',
    chartPlayground: 'Khu vực tạo biểu đồ', chartPlaygroundHelp: 'Chỉ dùng aggregate đã xác thực trên server. Tạo sẽ thêm kết quả vào canvas điều hành.', dimension: 'Chiều phân tích', metric: 'Chỉ số', aggregation: 'Phép tổng hợp', chartType: 'Loại biểu đồ', groupBy: 'Nhóm theo (không bắt buộc)', limit: 'Giới hạn', noGroup: 'Không nhóm', sum: 'Tổng', average: 'Trung bình', countRecords: 'Đếm bản ghi', bar: 'Cột', line: 'Đường', area: 'Miền', buildChart: 'Tạo biểu đồ', addFilter: 'Thêm bộ lọc', filterValue: 'Giá trị lọc', noFilters: 'Không có bộ lọc', validatedScope: 'Phạm vi đã xác thực', updating: 'Đang cập nhật', primaryTrend: 'Xu hướng chính', ranking: 'Xếp hạng / phân bố', customChart: 'Biểu đồ tùy chỉnh', group: 'Nhóm', none: 'Không có', type: 'Loại', viewRecords: 'Xem bản ghi phù hợp', chartNoRows: 'Không có hàng aggregate phù hợp với phạm vi đã xác thực.', chartConfigure: 'Cấu hình biểu đồ để yêu cầu aggregate đã xác thực từ server.', chartNeedsFields: 'Biểu đồ cần một chiều phân loại hoặc thời gian và một chỉ số số.', chartRejected: 'Yêu cầu biểu đồ bị từ chối.', chartFailed: 'Không thể tạo biểu đồ.', chartUpdateFailed: 'Không thể cập nhật biểu đồ.',
    deepDiveTitle: 'Khám phá chuyên sâu', deepDiveEyebrow: 'Trình khám phá raw data an toàn', deepDiveHelp: 'Tìm kiếm, lọc, sắp xếp và xuất chỉ các trường an toàn để trình bày từ run này.', exportFiltered: 'Xuất CSV đã lọc', preparingCsv: 'Đang chuẩn bị CSV…', sourceChart: 'Biểu đồ nguồn', groupedBy: 'nhóm theo', sourceScopeHelp: 'Bộ lọc đã xác thực được áp dụng sẵn bên dưới và được Data API kiểm tra lại.', searchData: 'Tìm kiếm dữ liệu hiển thị…', searchVisibleData: 'Tìm kiếm dữ liệu hiển thị', loadingResults: 'Đang tải kết quả', matchingRows: 'dòng phù hợp', columnsVisible: 'Cột', filters: 'Bộ lọc', validatedServer: 'Đã xác thực phía server', filterField: 'Trường lọc', filterOperator: 'Toán tử lọc', filterValueLabel: 'Giá trị lọc', number: 'Số', value: 'Giá trị', clearAll: 'Xóa tất cả', loadingData: 'Đang tải dữ liệu an toàn…', noMatchingRows: 'Không có dòng phù hợp', noMatchingHelp: 'Hãy đổi tìm kiếm hoặc bỏ một bộ lọc.', clearExplorer: 'Xóa trình khám phá', pageOf: 'Trang {page} trên {count}', previous: 'Trước', next: 'Tiếp', sortBy: 'Sắp xếp theo {column}', numericRequired: 'So sánh số cần một giá trị số.', duplicateFilter: 'Bộ lọc này đã được áp dụng.', dataLoadFailed: 'Không thể tải raw data.', exportFailed: 'Không thể xuất dữ liệu đã lọc.',
    dataHealthContext: 'Ngữ cảnh sức khỏe dữ liệu', safeFieldsAnalyzed: 'trường an toàn đã phân tích', sensitiveExcluded: 'trường nhạy cảm đã loại trừ', safeFields: 'Trường an toàn', sensitiveFieldsHidden: 'Trường nhạy cảm đã ẩn', fieldsMissing: 'Trường thiếu >10%', distinct: 'khác biệt', null: 'rỗng', preparingHealth: 'Đang chuẩn bị ngữ cảnh sức khỏe dữ liệu…',
    reportEyebrow: 'Bản tóm tắt có bằng chứng', reportSub: 'Nội dung tác giả viết tách biệt với aggregate đã xác thực trên server.', save: 'Lưu', saving: 'Đang lưu…', saved: 'Đã lưu', exportHtml: 'Xuất HTML', printPdf: 'In / PDF', reportTitleLabel: 'Tiêu đề báo cáo', executiveSummary: 'Tóm tắt điều hành', reportSummaryPlaceholder: 'Tóm tắt sẵn sàng cho quyết định, được neo rõ ràng vào bằng chứng bên dưới.', sectionsRecommendations: 'Phần và khuyến nghị', addSection: 'Thêm phần', sectionHeading: 'Tiêu đề phần', sectionCommentary: 'Nhận xét phần', commentary: 'Nhận xét', recommendedActions: 'Hành động đề xuất', recommendedActionsPlaceholder: 'Hành động đề xuất (mỗi dòng một mục)', removeSection: 'Xóa phần', pinnedArtifacts: 'Hiện vật đã xác thực được ghim', pinned: 'đã ghim', moveUp: 'Di chuyển hiện vật lên', moveDown: 'Di chuyển hiện vật xuống', removeArtifact: 'Xóa hiện vật', validatedArtifact: 'Hiện vật đã xác thực', authorAnnotation: 'Ghi chú của tác giả', reportEmpty: 'Ghim biểu đồ đã xác thực từ Tổng quan điều hành hoặc chat phân tích để thêm bằng chứng.', glossary: 'Thuật ngữ', glossaryHelp: 'Mục đã xác thực được tạo từ hiện vật đã ghim.', manualNotes: 'Ghi chú thủ công', manualNotesHelp: 'Do tác giả viết, không phải bằng chứng đã xác thực', manualNote: 'Ghi chú thuật ngữ thủ công', removeManualNote: 'Xóa ghi chú thủ công', addManualNote: 'Thêm ghi chú thủ công', reportSaveFailed: 'Không thể lưu báo cáo.',
    healthTitle: 'Sức khỏe dữ liệu & EDA', healthSub: 'Phạm vi, chất lượng, cardinality và phân bố có giới hạn. Giá trị nhạy cảm được loại trừ.', rowsLabel: 'Dòng', columnsLabel: 'Cột', analyzed: 'Đã phân tích', hidden: 'Trường nhạy cảm đã ẩn', label: 'Nhãn', secondaryGroup: 'Nhóm phụ',
  },
} as const;

export type CopyKey = keyof typeof copy.en;
export const text = (language: Language, key: CopyKey) => copy[language][key];
export const interpolate = (language: Language, key: CopyKey, values: Record<string, string | number>) => { let value: string = text(language, key); for (const [name, replacement] of Object.entries(values)) value = value.replaceAll(`{${name}}`, String(replacement)); return value; };
export function initialLanguage(): Language { const saved = localStorage.getItem('opendata.locale'); return saved === 'vi' ? 'vi' : DEFAULT_LANGUAGE; }
export function displayNumber(value: number, language: Language): string { return new Intl.NumberFormat(language === 'vi' ? 'vi-VN' : 'en-US').format(value); }
